import { OpenApiGeneratorV3 } from "@asteasolutions/zod-to-openapi";
import { openApiRegistry } from "./registry.js";
import { auth } from "../../infrastructure/auth/auth.js";
import { env } from "../../config/env.js";
import { logger } from "../logger/logger.js";

// Side-effect imports — each module's *.openapi.ts file registers its paths
// + schemas with the shared registry on module init. Add new modules here as
// they land (channels, messages, etc.).
import "../../modules/workspaces/workspaces.openapi.js";
import "../../modules/users/users.openapi.js";
import "../../modules/preferences/preferences.openapi.js";

// Register the session-cookie security scheme once so paths can reference it
// via `security: [{ sessionCookie: [] }]`.
openApiRegistry.registerComponent("securitySchemes", "sessionCookie", {
  type: "apiKey",
  in: "cookie",
  name: "better-auth.session_token",
  description:
    "Session cookie issued by Better Auth at POST /api/auth/sign-in/email.",
});

type OpenApiDocument = ReturnType<OpenApiGeneratorV3["generateDocument"]>;

const AUTH_PATH_PREFIX = "/api/auth";

/**
 * Builds the combined OpenAPI 3.0 document for the application API.
 *
 * Merges two sources:
 *   1. Paths registered by our modules via `openApiRegistry.registerPath(...)`
 *   2. Paths auto-generated by Better Auth's openAPI plugin (sign-up, sign-in,
 *      session, password reset, etc.), re-prefixed with `/api/auth` since
 *      Better Auth emits them relative to its own mount point.
 *
 * If the Better Auth plugin is missing or its API has changed, we log a
 * warning and serve only our own paths so /api/docs stays functional.
 *
 * Called once per process (lazy-cached in docs.routes.ts).
 */
export async function buildOpenApiDocument(): Promise<OpenApiDocument> {
  const ourDoc = generateOwnDocument();
  const authDoc = await tryGenerateAuthSchema();

  if (!authDoc) return ourDoc;

  return mergeDocuments(ourDoc, authDoc);
}

/**
 * Generates the OpenAPI doc fragment for routes we own.
 *
 * Called only by `buildOpenApiDocument`. Pulls every path + schema registered
 * via `openApiRegistry` at module load time.
 */
function generateOwnDocument(): OpenApiDocument {
  const generator = new OpenApiGeneratorV3(openApiRegistry.definitions);
  return generator.generateDocument({
    openapi: "3.0.0",
    info: {
      title: "Chat API",
      version: "0.1.0",
      description:
        "Multi-tenant messaging platform. Auth endpoints are sourced from " +
        "Better Auth's openAPI plugin and merged into this document.",
    },
    servers: [{ url: env.BETTER_AUTH_URL }],
  });
}

/**
 * Fetches Better Auth's auto-generated OpenAPI schema, defensively.
 *
 * Called only by `buildOpenApiDocument`. The method name comes from the
 * Better Auth openAPI plugin; if the plugin is missing or the library
 * renamed the method, we log and continue with just our own paths instead
 * of crashing the docs endpoint.
 */
async function tryGenerateAuthSchema(): Promise<OpenApiDocument | null> {
  try {
    const apiSurface = auth.api as unknown as {
      generateOpenAPISchema?: () => Promise<OpenApiDocument>;
    };
    if (typeof apiSurface.generateOpenAPISchema !== "function") {
      logger.warn(
        "Better Auth openAPI plugin not detected; auth routes will not appear in /api/docs.",
      );
      return null;
    }
    return await apiSurface.generateOpenAPISchema();
  } catch (err) {
    logger.warn(
      { err: err instanceof Error ? err.message : String(err) },
      "Failed to fetch Better Auth OpenAPI schema; auth routes will not appear in /api/docs.",
    );
    return null;
  }
}

/**
 * Merges Better Auth's document into ours.
 *
 * Called only by `buildOpenApiDocument`. Paths get re-prefixed unless they
 * already start with `/api/auth` (defensive against future Better Auth
 * versions that may emit absolute paths). Schemas and security schemes are
 * unioned; on key collision, ours wins.
 */
function mergeDocuments(
  ours: OpenApiDocument,
  theirs: OpenApiDocument,
): OpenApiDocument {
  type PathItemObject = NonNullable<OpenApiDocument["paths"]>[string];
  const prefixedAuthPaths: Record<string, PathItemObject> = {};
  for (const [path, ops] of Object.entries(theirs.paths ?? {})) {
    const finalPath = path.startsWith(AUTH_PATH_PREFIX)
      ? path
      : `${AUTH_PATH_PREFIX}${path}`;
    prefixedAuthPaths[finalPath] = ops;
  }

  return {
    ...ours,
    paths: { ...prefixedAuthPaths, ...ours.paths },
    components: {
      ...ours.components,
      schemas: {
        ...(theirs.components?.schemas ?? {}),
        ...(ours.components?.schemas ?? {}),
      },
      securitySchemes: {
        ...(theirs.components?.securitySchemes ?? {}),
        ...(ours.components?.securitySchemes ?? {}),
      },
    },
    tags: [...(theirs.tags ?? []), ...(ours.tags ?? [])],
  };
}
