// Better Auth owns identity tables. `User` here mirrors what Better Auth
// writes into the `users` table.
interface User {
  id: string;            // text, generated by Better Auth (not uuid)
  email: string;
  emailVerified: boolean;
  name: string;
  image: string | null;
  createdAt: Date;
  updatedAt: Date;
}
interface Workspace {
  id: string; // uuid
  slug: string;
  ownerId: string; // text — FKs User.id
}
interface Membership {
  userId: string; // text — FKs User.id
  workspaceId: string; // uuid
  role: Role;
}
interface TenantCatalog {
  workspaceId: string; // uuid
  schemaName: string;  // e.g. "tenant_acme" — Postgres schema in the shared DB
  schemaVersion: number;
}
interface Channel {
  id: string;
  type: ChannelType;
  name: string | null; // null for DMs — render from member names
  dmKey: string | null; // canonical key for dm/group_dm, null otherwise
  lastSeq: number;
}
interface ChannelMember {
  channelId: string; // uuid
  userId: string; // text — FKs User.id
  lastReadSeq: number;
}
interface Message {
  id: string; // uuid
  authorId: string; // text — FKs User.id
  body: string;
  clientId: string; // uuid
  seq: number;
  version: number;
  deleted: boolean;
}
interface MessageRevision {
  messageId: string; // uuid
  version: number;
  body: string;
  editedAt: Date;
}
interface Attachment {
  id: string; // uuid
  messageId: string; // uuid
  url: string;
}

// Enums and Type Aliases
type Role = "admin" | "member";
type ChannelType = "public" | "private" | "direct" | "group";

// public: visible to all workspace members
// private: visible to all but needs a permission to join
// direct: 1-on-1 channel between two users
// group: private channel with 3 or more members that only need an invite to join

// Relationships:
// User "1" --> "*" Membership
// Workspace "1" --> "*" Membership
// Workspace "1" --> "1" TenantCatalog
// Channel "1" --> "*" ChannelMember
// Channel "1" --> "*" Message
// Message "1" --> "*" MessageRevision
// Message "1" --> "*" Attachment
// ChannelMember ..> User : userId ref
// Message ..> User : authorId ref
